import { library } from '@fortawesome/fontawesome-svg-core';

import { fas, faLaughWink } from '@fortawesome/free-solid-svg-icons';
import { fab,
    faPython,
    faJs,
    faHtml5,
    faJava,
    faFacebookSquare,
    faGithubSquare,
    faLinkedin,
    faMedium,
    faBootstrap,
    faNode,
    faCss3Alt,
    faAngular,
    faJira,
    faLinux,
    faNpm,
    faUnity,
    faBitbucket,
    faDocker,
    faGithub
} from '@fortawesome/free-brands-svg-icons';

library.add( fab,fas,
    faPython,
    faJs,
    faHtml5,
    faJava,
    faFacebookSquare,
    faGithubSquare,
    faLinkedin,
    faMedium,
    faLaughWink,
    faBootstrap,
    faNode,
    faCss3Alt,
    faAngular,
    faJira,
    faLinux,
    faNpm,
    faUnity,
    faBitbucket,
    faDocker,
    faGithub
);